language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages 
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
            - libfftw3-dev

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='Cython jinja2 six setuptools h5py'
        - PIP_DEPENDENCIES='pytest pytest-benchmark pytest-xdist'
        - LIBRARY_PATH="$PWD/cextern/libFTR/lib/"
        - SYSTEM_FTR=''
    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:
    include:

        # Do a coverage test in Python 2.
        # - python: 2.7
        #   env: SETUP_CMD='test --coverage'
        
        - python: 2.6
          env: 
            - NUMPY_VERSION=1.9
            - ASTROPY_VERSION=1.0
            - SETUP_CMD='test'
            - PIP_DEPENDENCIES=''
        
        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test'
        - python: 3.5
          env: ASTROPY_VERSION=development SETUP_CMD='test'

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.8 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.7 SETUP_CMD='test'

    allow_failures:
      # Try with external libraries
      - python: 2.7
        env: SETUP_CMD='test' SYSTEM_FTR='true'

install:

    # CONDA
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - pip install --no-use-wheel pyzmq
    
    # System FTR library
    - if [[ $SYSTEM_FTR == 'true' ]]; then cd cextern/libFTR/ && make; fi
    - if [[ $SYSTEM_FTR == 'true' ]]; then cd ../../; fi
    - if [[ $SYSTEM_FTR == 'true' ]]; then python setup.py build_ext --use-system-ftr --library-dirs $PWD/cextern/libFTR/lib/ saveopts; fi
    
    # COVERAGE DEPENDENCIES
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then $PIP_INSTALL coverage==3.7.1 coveralls; fi

script:
   - python setup.py $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    # - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='packagename/tests/coveragerc'; fi
